on:
  workflow_call:
    inputs:
      image_dir:
        description: Which image to build (top level dir)
        type: string
        required: true

jobs:
  test-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2
      - uses: docker/setup-buildx-action@v2
        id: builder2
      - name: Build Image
        run: docker buildx build
        working_directory: ${{ image_dir }}

