on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test-build:
    strategy:
      matrix:
        image:
          - pyspark
          - tensorflow
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2
      - name: Build Image
        run: docker buildx build
        working-directory: ${{ matrix.image }}
