on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test-build:
    strategy:
      matrix:
        image-dir:
          - pyspark
          - tensorflow
    uses: ./github/workflows/build.yaml
    with:
      image_dir: ${{ matrix.image-dir }}
