on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test-build:
    strategy:
      matrix:
        image:
          - pyspark
          - tensorflow
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2
      - name: Build Image
        uses: docker/build-push-action@v4
        with:
          context: ${{ matrix.image }}
          push: false
          cache-from: type=gha,scope=${{ github.ref_name }}-${{ matrix.image }}
          cache-to: type=gha,mode=max,scope=${{ github.ref_name }}-${{ matrix.image }}

